llm:
    chatglm2: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-new-chatbot/models/chatglm2-6b
    GPT4ALL_PATH: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-new-chatbot/models
    GPTEALL_MODEL: ggml-gpt4all-j-v1.3-groovy.bin
    Vicuna-13B: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-new-chatbot/models/vicuna-13b-v1.3
    baichuan-7b: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-new-chatbot/models/Baichuan-7B
    mpt-7b-chat: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-new-chatbot/models/mpt-7b-chat
    llama2-chat: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-new-chatbot/models/Llama-2-7b-chat-hf
    gpu: True
    embedding: all-MiniLM-L6-v2
    model_type: bert
vector:
    chunk_size: 500
    chunk_overlap: 50
    api_store: /hps/nobackup/juan/pride/chatbot/pride-prd-chatbot/pride-chatbot/vector_store/
    cli_store: ./vector/


