llm:
    chatglm2: /root/autodl-tmp/chatglm2-6b
    GPT4ALL_PATH: /root/autodl-tmp
    GPTEALL_MODEL: ggml-gpt4all-j-v1.3-groovy.bin
    Vicuna-13B: /root/autodl-tmp/vicuna-13b-v1.3
    baichuan-7b: /root/autodl-tmp/Baichuan-7B
    mbt-7b-chat: /root/autodl-tmp/mpt-7b-chat
    llama2-chat: /root/autodl-tmp/Llama-2-7b-chat-hf
    gpu: True
    embedding: all-MiniLM-L6-v2
    model_type: bert
vector:
    chunk_size: 500
    chunk_overlap: 50
    api_store: ./vector_store/
    cli_store: ./vector/


